name: Coveralls

on:
  push:
    branches:
      - main

jobs:
  get-taos-version:
    runs-on: ubuntu-latest
    
    outputs:
      taos-version: ${{ steps.gettaosversion.outputs.version }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Get taos version
        id: gettaosversion
        run: echo "version=$(cat TAOSVERSION)" >> $GITHUB_OUTPUT
  
  coverage:
    needs: get-taos-version
    runs-on: ubuntu-latest
    
    services:
      tdengine:
        image: tdengine/tdengine:${{ needs.get-taos-version.outputs.taos-version }}
        ports:
          - 6030:6030
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: dtolnay/rust-toolchain@nightly
      
      - uses: taiki-e/install-action@cargo-tarpaulin
      
      - name: Cache taosc
        id: cache-taosc
        uses: actions/cache@v3
        with:
          key: taosc-${{ needs.get-taos-version.outputs.taos-version }}
          path: TDengine-client-${{ needs.get-taos-version.outputs.taos-version }}
    
      - if: ${{ steps.cache-taosc.outputs.cache-hit != 'true' }}
        name: Get taosc
        run: |
          curl -sO https://www.taosdata.com/assets-download/3.0/TDengine-client-${{ needs.get-taos-version.outputs.taos-version }}-Linux-x64-Lite.tar.gz
          tar zxf TDengine-client-${{ needs.get-taos-version.outputs.taos-version }}-Linux-x64-Lite.tar.gz
      
      - name: Install taosc
        run: |
          cd TDengine-client-${{ needs.get-taos-version.outputs.taos-version}}
          ./install_client.sh
            
      - name: Coverage
        run: cargo +nightly tarpaulin --follow-exec --post-test-delay 10 --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }} -- --test-threads=1
